'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from './Navbar/Navbar';
import { usePathname } from 'next/navigation';
import { MantineProvider, createTheme } from '@mantine/core';
import { store, wrapper } from '@/shared/redux/store';
import { Provider, useDispatch } from 'react-redux';
import { setAuthState } from '@/shared/redux/authSlice';
import { supabase } from '@/shared/supabaseConfig';
import router from 'next/router';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const theme = createTheme({});
function RootLayout({ children }: { children: React.ReactNode }) {
  const path = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <MantineProvider theme={theme}>
            <InnerRoot>
              <>
                {path
                  .split('/')
                  .some((i) => i === 'Login' || i === 'SignUp') ? (
                  <></>
                ) : (
                  <Navbar />
                )}
                {children}
              </>
            </InnerRoot>
          </MantineProvider>
        </Provider>
      </body>
    </html>
  );
}

const InnerRoot = ({ children }: { children: React.ReactNode }) => {
  const dispatch = useDispatch();
  useEffect(() => {
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event) => {
      if (event === 'SIGNED_IN' || event === 'INITIAL_SESSION') {
        dispatch(setAuthState(supabase));
      } else if (event === 'SIGNED_OUT') {
        dispatch(setAuthState(null));
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [router, supabase]);

  return children;
};
export default RootLayout;
