# TODO tests are not yet completed
version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.0

jobs:
  component-and-e2e-tests:
    docker:
      - image: node:latest
    steps:
      - checkout

      - run:
          name: install pnpm
          command: "npm i -g pnpm"
          
      - run:
          name: install deps
          command: "npm i"

      - run:
          name: update apt
          command: apt-get update

      - run:
          name: install system deps
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run:
          name: Run app
          command: "pnpm dev:client"
          background: true

      - cypress/run-tests:
          cypress-command: "npx wait-on@latest http://localhost:3000 && npx cypress run"
          working-directory: app


      - store_artifacts:
          path: ./app/cypress/screenshots
          when: on_fail

  publish-to-main-branch:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "8d:81:26:dd:de:75:b3:c2:96:f2:c6:47:2f:8f:fb:8f"

      - run:
          name: Push to production branch
          command: git push origin main2.0:main

  deploy-to-vercel:
    docker:
      - image: node:latest
        environment:
          VERCEL_ORG_ID: $VERCEL_ORG_ID
          VERCEL_PASSWORD_ID: $VERCEL_PASSWORD_ID
    steps:
      - checkout

      - run:
          name: Install vercel
          command: npm i -g vercel@latest pnpm

      - run:
          name: PULL VERCEL ENVIRONMENT
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - run:
          name: BUILD PROJECT
          command: vercel build --prod --token=$VERCEL_TOKEN

      - run:
          name: DEPLOY PROJECT
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  the-great-gatsby:
    jobs:

      - cypress/run:
          install-command: sudo npm i -g pnpm && npm install
          # install-browsers: true
          start-command: 'pnpm dev'
          working-directory: app
          cypress-command: 'npx wait-on@latest http://localhost:3000 && npx cypress run'

      - publish-to-main-branch:
          requires:
            - cypress/run

      - deploy-to-vercel:
          requires:
            - cypress/run
            - publish-to-main-branch

      # - component-and-e2e-tests:
      #     filters:
      #       branches:
      #         only:
      #           - main2.0
