# TODO tests are not yet completed
version: 2.1
setup: true

jobs:
  e2e-tests:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: FRONTEND
          command: echo FRONTEND

workflows:
  the-great-gatsby:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only:
                - main
