version: 2.1

jobs:
  create-docker-image-and-publish-to-dockerhub:
    docker:
      - image: docker:20.10.11
    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Docker login
          command: echo LOGIN

workflows:
  the-great-depression:
    jobs:
      - create-docker-image-and-publish-to-dockerhub